# Generated by Django 3.0.6 on 2020-06-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notification_notificationstatus_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='time',
        ),
    ]
